rc.d script added

diff --git a/usr/local/bin/blockor b/usr/local/bin/blockor
--- a/usr/local/bin/blockor
+++ b/usr/local/bin/blockor
@@ -4,28 +4,25 @@
 # All rights reserved.
 
 ## version
-blockor_version='0.0.1'
+version='0.1.0'
 
 PATH=${PATH}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
 
+. /usr/local/etc/blockor.conf
 
-if [ -r "/usr/local/etc/blockor.conf" ]; then
-    . /usr/local/etc/blockor.conf
-fi
-
-usage() {
+blockor_usage() {
     cat << EOF
 Blockor protects FreeBSD, OpenBSD servers from brute-force attacks.
 Usage:
   blockor command [args]
 Available Commands:
-  init          Create blockor.conf file with default value.
-  start         Start the blockord.
-  stop          Stop the blockord.
-  add         	Add IP to blocked IP list.
-  delete        Remove IP from blocked IP list.
-  list         	List blocked IP list.
-  status        Blocked IP list summary.
+  check         Check blockor.conf file and show "pf.conf" config.
+  start         Start the blockord daemon.
+  stop          Stop the blockord daemon.
+  add           Add IP to blocked list.
+  remove        Remove IP from blocked list.
+  list          Show blocked list with the failed count.
+  status        Running or Stopped.
 Use "blockor -v|--version" for version information.
 Use "blockor command -h|--help" for more information about a command.
 EOF
@@ -34,104 +31,90 @@ EOF
 
 permission_check() {
     if [ $(id -u) -ne 0 ]; then
-        echo "blockor: permission denied. root|doas|sudo required"
+        echo "blockor(permission denied). root|doas|sudo required"
         exit 1
     fi
 }
 
-version() {
-    echo ${blockor_version}
+blockor_version() {
+    echo "blockor(${version})"
     exit 0
 }
 
-init() {
-    if [ ! -d "/usr/local/etc" ]; then
-        echo "Directory /usr/local/etc not found."
-        mkdir /usr/local/etc
-    fi
-
-    conf = "/usr/local/etc/blockor.conf"
-    sample_conf = "/usr/local/share/examples/blockor/blockor.sample.conf"
-
-    if [ -z $blockor_config ]
-    then
-        os=$(uname -sr | awk '{print $1}')
-        if [ $os == 'OpenBSD' ]
-        then
-            cat $sample_conf > $conf
-        else
-            sed 's/authlog/auth.log/' $sample_conf > $conf
-        fi
-        echo 'File' $conf 'created.'
+blockor_check() {
+    blockor_conf="/usr/local/etc/blockor.conf"
+    if [ ! -r $blockor_conf ]; then
+        echo "blockor($blockor_conf not found)"
+        echo "example: /usr/local/share/examples/blockor/blockor.example.conf"
     else
-        echo 'File' $conf 'alrealy exits.'
+        echo "blockor(ok)"
     fi
-
-    echo
     cat <<EOF
-Add these lines to pf.conf file.
-
+Add these two lines to pf.conf.
 table <blockor> persist
 block drop in quick on egress from <blockor> to any
 EOF
 exit 0
 }
 
-start() {
+blockor_start() {
+    if [ $(ps ax | awk '/libexec/ && /blockord.sh/' | grep -v awk | wc -l) -gt 0 ]; then
+        echo 'blockord(already running)'
+        exit 1
+    fi
     nohup $blockord > $blockor_log_file &
+    echo 'blockord(ok)'
     exit 0
 }
 
-stop() {
-    ps ax | grep "$blockord" | awk '{print $1}' | xargs kill -9
+blockor_stop() {
+    ps ax | awk '/libexec/ && /blockord.sh/' | grep -v awk |  awk '{print $1}' | xargs kill -9
+    ps ax | awk '/tail -n 0 -f/ && /auth.?log/' | grep -v awk | awk '{print $1}' | xargs kill -9
+    echo 'blockord(stopped)'
     exit 0
 }
 
-add() {
+blockor_add() {
     IP=$(echo ${1} | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
     shift
-    if [ -z $IP]
-    then
-        echo 'Invalid IP. Please provide a valid IP.'
+    if [ -z $IP]; then
+        echo 'blockor(invalid IP)'
         exit 1
     else
         pfctl -t blockor -T add $IP
+        echo 'blockor(added)'
     fi
     exit 0
 }
 
-delete() {
+blockor_remove() {
     IP=$(echo ${1} | grep -oE '([0-9]{1,3}\.){3}[0-9]{1,3}')
     shift
-    if [ -z $IP]
-    then
-        echo 'Invalid IP. Please provide a valid IP.'
+    if [ -z $IP]; then
+        echo 'blockor(invalid IP)'
         exit 1
     else
         pfctl -t blockor -T delete $IP
+        echo 'blockor(removed)'
     fi
     exit 0
 }
 
-list() {
-    all=${1}
-    shift
-    if [ $all=='all' || $all=='-a' ]
-    then
-        echo "  Count  IP"
-        cat $blockor_file | sort | uniq -c | sort -nr
-    else
-        echo "Blocked IP list:"
-        pfctl -t blockor -T show
-    fi
-    exit 0
-}
-
-status() {
+blockor_list() {
     total=$(pfctl -t blockor -T show | wc -l)
-    echo 'Total' $total 'IP blocked'
-    echo 'Blocked IP list:'
+    echo 'Total' $total 'IP(s) blocked'
     pfctl -t blockor -T show
+    echo "count  IP"
+    cat $blockor_file | sort | uniq -c | sort -nr
+    exit 0
+}
+
+blockor_status() {
+    if [ $(ps ax | awk '/libexec/ && /blockord.sh/' | grep -v awk | wc -l) -gt 0 ]; then
+        echo 'blockord(running)'
+    else
+        echo 'blockord(stopped)'
+    fi
     exit 0
 }
 
@@ -142,40 +125,40 @@ shift
 
 case ${CMD} in
 version|-v|--version)
-    version
+    blockor_version
     ;;
 help|-h|--help)
-    usage
+    blockor_usage
     ;;
-init|--init)
+check|--check)
     permission_check
-    init
+    blockor_check
     ;;
 start|--start)
     permission_check
-    start
+    blockor_start
     ;;
 stop|--stop)
     permission_check
-    stop
+    blockor_stop
     ;;
 add|-a|--add)
     permission_check
-    add
+    blockor_add
     ;;
-delete|-d|--delete)
+remove|-r|--remove)
     permission_check
-    delete
+    blockor_remove
     ;;
 list|-l|--list)
     permission_check
-    list
+    blockor_list
     ;;
 status|-s|--status)
     permission_check
-    status
+    blockor_status
     ;;
 *)
-    usage    
+    blockor_usage
     ;;
 esac
